language: node_js
node_js:
- '0.10'
before_script:
- npm install
script:
- "./grunt karma:continuous-integration"
env:
  matrix:
    secure: w/gr553UtlnGoCKtPWZqbVoDQTT0CgBvZA6gQmuk1TAt5z8iP4U4KJrhtoinqZF2daL6SmETP926n67aT6AbuD1y9RbkBDjsAQ+yVnz9H0fxp3K+r1F7f7kHOqGKEWDq3+SAgpcXlvmztu80LPz/u5ZzvdAWJO3xFbQFNDygPU0oneeV3Aaq1YQa6ve5iHwhDHALJ3aEOoWA/+Jrv2npdb2C0x7XBUH83EMsLN+/DRYIP68/9mUxiActCvs6Wz30CLXyU1nQ8RFphtntI55SfL2uHwSog32VMrIIMJUkhwsmkSwZAElHEv4H96EzJYHqaDxtq2LEuQM6TLNiNbbfeRVvH3GXwzY8ONYT9KWRj5hjXyplXTo/8AjKkUDh56Vg6soYqbu7FAL6/Us8GyK02wB0hivWx9jEfYfwzjcRWDOtQsM7dnpo1Kq03h4Nw0iJ7XpxHGwBsCiUFDi4pT7A04whRcY0vGR5AJcGGsbchkydTsO2DTGTld9YUzfZrJjoRGDtq9I1bfRxnHd8MFXM1GxcQLIcAjcqtLCPgaWc64HYxlQJK775NKOsaClmCnlS4cJusUvSiZpSRXNgLcKWtWgZRlXxPcaAENkw7j+XRCrmYnZDw/+V9bIaWuPnSaTeiXXemcZmxFGW2BjLVdcN6YqAanjOwYIH/uu3C+J6Jek=
